// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/gen0cide/laforge/ent/environment"
	"github.com/gen0cide/laforge/ent/replaypcap"
	"github.com/google/uuid"
)

// ReplayPcap is the model entity for the ReplayPcap schema.
type ReplayPcap struct {
	config ` json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// HclID holds the value of the "hcl_id" field.
	HclID string `json:"hcl_id,omitempty" hcl:"id,label"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty" hcl:"source_type,attr"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty" hcl:"source,attr"`
	// Template holds the value of the "template" field.
	Template bool `json:"template,omitempty" hcl:"template,optional"`
	// Disabled holds the value of the "disabled" field.
	Disabled bool `json:"disabled,omitempty" hcl:"disabled,optional"`
	// AbsPath holds the value of the "abs_path" field.
	AbsPath string `json:"abs_path,omitempty" hcl:"abs_path,optional"`
	// Tags holds the value of the "tags" field.
	Tags map[string]string `json:"tags,omitempty" hcl:"tags,optional"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReplayPcapQuery when eager-loading is set.
	Edges ReplayPcapEdges `json:"edges"`

	// Edges put into the main struct to be loaded via hcl
	// Environment holds the value of the Environment edge.
	HCLEnvironment *Environment `json:"Environment,omitempty"`
	//
	environment_replay_pcaps *uuid.UUID
}

// ReplayPcapEdges holds the relations/edges for other nodes in the graph.
type ReplayPcapEdges struct {
	// Environment holds the value of the Environment edge.
	Environment *Environment `json:"Environment,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EnvironmentOrErr returns the Environment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReplayPcapEdges) EnvironmentOrErr() (*Environment, error) {
	if e.loadedTypes[0] {
		if e.Environment == nil {
			// The edge Environment was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: environment.Label}
		}
		return e.Environment, nil
	}
	return nil, &NotLoadedError{edge: "Environment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReplayPcap) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case replaypcap.FieldTags:
			values[i] = new([]byte)
		case replaypcap.FieldTemplate, replaypcap.FieldDisabled:
			values[i] = new(sql.NullBool)
		case replaypcap.FieldHclID, replaypcap.FieldSourceType, replaypcap.FieldSource, replaypcap.FieldAbsPath:
			values[i] = new(sql.NullString)
		case replaypcap.FieldID:
			values[i] = new(uuid.UUID)
		case replaypcap.ForeignKeys[0]: // environment_replay_pcaps
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type ReplayPcap", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReplayPcap fields.
func (rp *ReplayPcap) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case replaypcap.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				rp.ID = *value
			}
		case replaypcap.FieldHclID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hcl_id", values[i])
			} else if value.Valid {
				rp.HclID = value.String
			}
		case replaypcap.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				rp.SourceType = value.String
			}
		case replaypcap.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				rp.Source = value.String
			}
		case replaypcap.FieldTemplate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field template", values[i])
			} else if value.Valid {
				rp.Template = value.Bool
			}
		case replaypcap.FieldDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field disabled", values[i])
			} else if value.Valid {
				rp.Disabled = value.Bool
			}
		case replaypcap.FieldAbsPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field abs_path", values[i])
			} else if value.Valid {
				rp.AbsPath = value.String
			}
		case replaypcap.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rp.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case replaypcap.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field environment_replay_pcaps", values[i])
			} else if value.Valid {
				rp.environment_replay_pcaps = new(uuid.UUID)
				*rp.environment_replay_pcaps = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// QueryEnvironment queries the "Environment" edge of the ReplayPcap entity.
func (rp *ReplayPcap) QueryEnvironment() *EnvironmentQuery {
	return (&ReplayPcapClient{config: rp.config}).QueryEnvironment(rp)
}

// Update returns a builder for updating this ReplayPcap.
// Note that you need to call ReplayPcap.Unwrap() before calling this method if this ReplayPcap
// was returned from a transaction, and the transaction was committed or rolled back.
func (rp *ReplayPcap) Update() *ReplayPcapUpdateOne {
	return (&ReplayPcapClient{config: rp.config}).UpdateOne(rp)
}

// Unwrap unwraps the ReplayPcap entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rp *ReplayPcap) Unwrap() *ReplayPcap {
	tx, ok := rp.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReplayPcap is not a transactional entity")
	}
	rp.config.driver = tx.drv
	return rp
}

// String implements the fmt.Stringer.
func (rp *ReplayPcap) String() string {
	var builder strings.Builder
	builder.WriteString("ReplayPcap(")
	builder.WriteString(fmt.Sprintf("id=%v", rp.ID))
	builder.WriteString(", hcl_id=")
	builder.WriteString(rp.HclID)
	builder.WriteString(", source_type=")
	builder.WriteString(rp.SourceType)
	builder.WriteString(", source=")
	builder.WriteString(rp.Source)
	builder.WriteString(", template=")
	builder.WriteString(fmt.Sprintf("%v", rp.Template))
	builder.WriteString(", disabled=")
	builder.WriteString(fmt.Sprintf("%v", rp.Disabled))
	builder.WriteString(", abs_path=")
	builder.WriteString(rp.AbsPath)
	builder.WriteString(", tags=")
	builder.WriteString(fmt.Sprintf("%v", rp.Tags))
	builder.WriteByte(')')
	return builder.String()
}

// ReplayPcaps is a parsable slice of ReplayPcap.
type ReplayPcaps []*ReplayPcap

func (rp ReplayPcaps) config(cfg config) {
	for _i := range rp {
		rp[_i].config = cfg
	}
}
