// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gen0cide/laforge/ent/environment"
	"github.com/gen0cide/laforge/ent/predicate"
	"github.com/gen0cide/laforge/ent/replaypcap"
	"github.com/google/uuid"
)

// ReplayPcapQuery is the builder for querying ReplayPcap entities.
type ReplayPcapQuery struct {
	config
	limit           *int
	offset          *int
	unique          *bool
	order           []OrderFunc
	fields          []string
	predicates      []predicate.ReplayPcap
	withEnvironment *EnvironmentQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReplayPcapQuery builder.
func (rpq *ReplayPcapQuery) Where(ps ...predicate.ReplayPcap) *ReplayPcapQuery {
	rpq.predicates = append(rpq.predicates, ps...)
	return rpq
}

// Limit adds a limit step to the query.
func (rpq *ReplayPcapQuery) Limit(limit int) *ReplayPcapQuery {
	rpq.limit = &limit
	return rpq
}

// Offset adds an offset step to the query.
func (rpq *ReplayPcapQuery) Offset(offset int) *ReplayPcapQuery {
	rpq.offset = &offset
	return rpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rpq *ReplayPcapQuery) Unique(unique bool) *ReplayPcapQuery {
	rpq.unique = &unique
	return rpq
}

// Order adds an order step to the query.
func (rpq *ReplayPcapQuery) Order(o ...OrderFunc) *ReplayPcapQuery {
	rpq.order = append(rpq.order, o...)
	return rpq
}

// QueryEnvironment chains the current query on the "Environment" edge.
func (rpq *ReplayPcapQuery) QueryEnvironment() *EnvironmentQuery {
	query := &EnvironmentQuery{config: rpq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(replaypcap.Table, replaypcap.FieldID, selector),
			sqlgraph.To(environment.Table, environment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, replaypcap.EnvironmentTable, replaypcap.EnvironmentColumn),
		)
		fromU = sqlgraph.SetNeighbors(rpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ReplayPcap entity from the query.
// Returns a *NotFoundError when no ReplayPcap was found.
func (rpq *ReplayPcapQuery) First(ctx context.Context) (*ReplayPcap, error) {
	nodes, err := rpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{replaypcap.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rpq *ReplayPcapQuery) FirstX(ctx context.Context) *ReplayPcap {
	node, err := rpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReplayPcap ID from the query.
// Returns a *NotFoundError when no ReplayPcap ID was found.
func (rpq *ReplayPcapQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{replaypcap.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rpq *ReplayPcapQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReplayPcap entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReplayPcap entity is found.
// Returns a *NotFoundError when no ReplayPcap entities are found.
func (rpq *ReplayPcapQuery) Only(ctx context.Context) (*ReplayPcap, error) {
	nodes, err := rpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{replaypcap.Label}
	default:
		return nil, &NotSingularError{replaypcap.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rpq *ReplayPcapQuery) OnlyX(ctx context.Context) *ReplayPcap {
	node, err := rpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReplayPcap ID in the query.
// Returns a *NotSingularError when more than one ReplayPcap ID is found.
// Returns a *NotFoundError when no entities are found.
func (rpq *ReplayPcapQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{replaypcap.Label}
	default:
		err = &NotSingularError{replaypcap.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rpq *ReplayPcapQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReplayPcaps.
func (rpq *ReplayPcapQuery) All(ctx context.Context) ([]*ReplayPcap, error) {
	if err := rpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rpq *ReplayPcapQuery) AllX(ctx context.Context) []*ReplayPcap {
	nodes, err := rpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReplayPcap IDs.
func (rpq *ReplayPcapQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := rpq.Select(replaypcap.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rpq *ReplayPcapQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rpq *ReplayPcapQuery) Count(ctx context.Context) (int, error) {
	if err := rpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rpq *ReplayPcapQuery) CountX(ctx context.Context) int {
	count, err := rpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rpq *ReplayPcapQuery) Exist(ctx context.Context) (bool, error) {
	if err := rpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rpq *ReplayPcapQuery) ExistX(ctx context.Context) bool {
	exist, err := rpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReplayPcapQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rpq *ReplayPcapQuery) Clone() *ReplayPcapQuery {
	if rpq == nil {
		return nil
	}
	return &ReplayPcapQuery{
		config:          rpq.config,
		limit:           rpq.limit,
		offset:          rpq.offset,
		order:           append([]OrderFunc{}, rpq.order...),
		predicates:      append([]predicate.ReplayPcap{}, rpq.predicates...),
		withEnvironment: rpq.withEnvironment.Clone(),
		// clone intermediate query.
		sql:    rpq.sql.Clone(),
		path:   rpq.path,
		unique: rpq.unique,
	}
}

// WithEnvironment tells the query-builder to eager-load the nodes that are connected to
// the "Environment" edge. The optional arguments are used to configure the query builder of the edge.
func (rpq *ReplayPcapQuery) WithEnvironment(opts ...func(*EnvironmentQuery)) *ReplayPcapQuery {
	query := &EnvironmentQuery{config: rpq.config}
	for _, opt := range opts {
		opt(query)
	}
	rpq.withEnvironment = query
	return rpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		HclID string `json:"hcl_id,omitempty" hcl:"id,label"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReplayPcap.Query().
//		GroupBy(replaypcap.FieldHclID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rpq *ReplayPcapQuery) GroupBy(field string, fields ...string) *ReplayPcapGroupBy {
	grbuild := &ReplayPcapGroupBy{config: rpq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rpq.sqlQuery(ctx), nil
	}
	grbuild.label = replaypcap.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		HclID string `json:"hcl_id,omitempty" hcl:"id,label"`
//	}
//
//	client.ReplayPcap.Query().
//		Select(replaypcap.FieldHclID).
//		Scan(ctx, &v)
func (rpq *ReplayPcapQuery) Select(fields ...string) *ReplayPcapSelect {
	rpq.fields = append(rpq.fields, fields...)
	selbuild := &ReplayPcapSelect{ReplayPcapQuery: rpq}
	selbuild.label = replaypcap.Label
	selbuild.flds, selbuild.scan = &rpq.fields, selbuild.Scan
	return selbuild
}

func (rpq *ReplayPcapQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rpq.fields {
		if !replaypcap.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rpq.path != nil {
		prev, err := rpq.path(ctx)
		if err != nil {
			return err
		}
		rpq.sql = prev
	}
	return nil
}

func (rpq *ReplayPcapQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReplayPcap, error) {
	var (
		nodes       = []*ReplayPcap{}
		withFKs     = rpq.withFKs
		_spec       = rpq.querySpec()
		loadedTypes = [1]bool{
			rpq.withEnvironment != nil,
		}
	)
	if rpq.withEnvironment != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, replaypcap.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*ReplayPcap).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &ReplayPcap{config: rpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rpq.withEnvironment; query != nil {
		if err := rpq.loadEnvironment(ctx, query, nodes, nil,
			func(n *ReplayPcap, e *Environment) { n.Edges.Environment = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rpq *ReplayPcapQuery) loadEnvironment(ctx context.Context, query *EnvironmentQuery, nodes []*ReplayPcap, init func(*ReplayPcap), assign func(*ReplayPcap, *Environment)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ReplayPcap)
	for i := range nodes {
		if nodes[i].environment_replay_pcaps == nil {
			continue
		}
		fk := *nodes[i].environment_replay_pcaps
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(environment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "environment_replay_pcaps" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rpq *ReplayPcapQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rpq.querySpec()
	_spec.Node.Columns = rpq.fields
	if len(rpq.fields) > 0 {
		_spec.Unique = rpq.unique != nil && *rpq.unique
	}
	return sqlgraph.CountNodes(ctx, rpq.driver, _spec)
}

func (rpq *ReplayPcapQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rpq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rpq *ReplayPcapQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   replaypcap.Table,
			Columns: replaypcap.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: replaypcap.FieldID,
			},
		},
		From:   rpq.sql,
		Unique: true,
	}
	if unique := rpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, replaypcap.FieldID)
		for i := range fields {
			if fields[i] != replaypcap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rpq *ReplayPcapQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rpq.driver.Dialect())
	t1 := builder.Table(replaypcap.Table)
	columns := rpq.fields
	if len(columns) == 0 {
		columns = replaypcap.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rpq.sql != nil {
		selector = rpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rpq.unique != nil && *rpq.unique {
		selector.Distinct()
	}
	for _, p := range rpq.predicates {
		p(selector)
	}
	for _, p := range rpq.order {
		p(selector)
	}
	if offset := rpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReplayPcapGroupBy is the group-by builder for ReplayPcap entities.
type ReplayPcapGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rpgb *ReplayPcapGroupBy) Aggregate(fns ...AggregateFunc) *ReplayPcapGroupBy {
	rpgb.fns = append(rpgb.fns, fns...)
	return rpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rpgb *ReplayPcapGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rpgb.path(ctx)
	if err != nil {
		return err
	}
	rpgb.sql = query
	return rpgb.sqlScan(ctx, v)
}

func (rpgb *ReplayPcapGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rpgb.fields {
		if !replaypcap.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rpgb *ReplayPcapGroupBy) sqlQuery() *sql.Selector {
	selector := rpgb.sql.Select()
	aggregation := make([]string, 0, len(rpgb.fns))
	for _, fn := range rpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rpgb.fields)+len(rpgb.fns))
		for _, f := range rpgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rpgb.fields...)...)
}

// ReplayPcapSelect is the builder for selecting fields of ReplayPcap entities.
type ReplayPcapSelect struct {
	*ReplayPcapQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rps *ReplayPcapSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rps.prepareQuery(ctx); err != nil {
		return err
	}
	rps.sql = rps.ReplayPcapQuery.sqlQuery(ctx)
	return rps.sqlScan(ctx, v)
}

func (rps *ReplayPcapSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rps.sql.Query()
	if err := rps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
