// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gen0cide/laforge/ent/environment"
	"github.com/gen0cide/laforge/ent/predicate"
	"github.com/gen0cide/laforge/ent/user"
	"github.com/gen0cide/laforge/ent/validation"
	"github.com/google/uuid"
)

// ValidationUpdate is the builder for updating Validation entities.
type ValidationUpdate struct {
	config
	hooks    []Hook
	mutation *ValidationMutation
}

// Where appends a list predicates to the ValidationUpdate builder.
func (vu *ValidationUpdate) Where(ps ...predicate.Validation) *ValidationUpdate {
	vu.mutation.Where(ps...)
	return vu
}

// SetHclID sets the "hcl_id" field.
func (vu *ValidationUpdate) SetHclID(s string) *ValidationUpdate {
	vu.mutation.SetHclID(s)
	return vu
}

// SetValidationType sets the "validation_type" field.
func (vu *ValidationUpdate) SetValidationType(vt validation.ValidationType) *ValidationUpdate {
	vu.mutation.SetValidationType(vt)
	return vu
}

// SetHash sets the "hash" field.
func (vu *ValidationUpdate) SetHash(s string) *ValidationUpdate {
	vu.mutation.SetHash(s)
	return vu
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableHash(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetHash(*s)
	}
	return vu
}

// ClearHash clears the value of the "hash" field.
func (vu *ValidationUpdate) ClearHash() *ValidationUpdate {
	vu.mutation.ClearHash()
	return vu
}

// SetRegex sets the "regex" field.
func (vu *ValidationUpdate) SetRegex(s string) *ValidationUpdate {
	vu.mutation.SetRegex(s)
	return vu
}

// SetNillableRegex sets the "regex" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableRegex(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetRegex(*s)
	}
	return vu
}

// ClearRegex clears the value of the "regex" field.
func (vu *ValidationUpdate) ClearRegex() *ValidationUpdate {
	vu.mutation.ClearRegex()
	return vu
}

// SetIP sets the "ip" field.
func (vu *ValidationUpdate) SetIP(s string) *ValidationUpdate {
	vu.mutation.SetIP(s)
	return vu
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableIP(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetIP(*s)
	}
	return vu
}

// ClearIP clears the value of the "ip" field.
func (vu *ValidationUpdate) ClearIP() *ValidationUpdate {
	vu.mutation.ClearIP()
	return vu
}

// SetURL sets the "url" field.
func (vu *ValidationUpdate) SetURL(s string) *ValidationUpdate {
	vu.mutation.SetURL(s)
	return vu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableURL(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetURL(*s)
	}
	return vu
}

// ClearURL clears the value of the "url" field.
func (vu *ValidationUpdate) ClearURL() *ValidationUpdate {
	vu.mutation.ClearURL()
	return vu
}

// SetPort sets the "port" field.
func (vu *ValidationUpdate) SetPort(i int) *ValidationUpdate {
	vu.mutation.ResetPort()
	vu.mutation.SetPort(i)
	return vu
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillablePort(i *int) *ValidationUpdate {
	if i != nil {
		vu.SetPort(*i)
	}
	return vu
}

// AddPort adds i to the "port" field.
func (vu *ValidationUpdate) AddPort(i int) *ValidationUpdate {
	vu.mutation.AddPort(i)
	return vu
}

// ClearPort clears the value of the "port" field.
func (vu *ValidationUpdate) ClearPort() *ValidationUpdate {
	vu.mutation.ClearPort()
	return vu
}

// SetHostname sets the "hostname" field.
func (vu *ValidationUpdate) SetHostname(s string) *ValidationUpdate {
	vu.mutation.SetHostname(s)
	return vu
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableHostname(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetHostname(*s)
	}
	return vu
}

// ClearHostname clears the value of the "hostname" field.
func (vu *ValidationUpdate) ClearHostname() *ValidationUpdate {
	vu.mutation.ClearHostname()
	return vu
}

// SetNameservers sets the "nameservers" field.
func (vu *ValidationUpdate) SetNameservers(s []string) *ValidationUpdate {
	vu.mutation.SetNameservers(s)
	return vu
}

// ClearNameservers clears the value of the "nameservers" field.
func (vu *ValidationUpdate) ClearNameservers() *ValidationUpdate {
	vu.mutation.ClearNameservers()
	return vu
}

// SetPackageName sets the "package_name" field.
func (vu *ValidationUpdate) SetPackageName(s string) *ValidationUpdate {
	vu.mutation.SetPackageName(s)
	return vu
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillablePackageName(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetPackageName(*s)
	}
	return vu
}

// ClearPackageName clears the value of the "package_name" field.
func (vu *ValidationUpdate) ClearPackageName() *ValidationUpdate {
	vu.mutation.ClearPackageName()
	return vu
}

// SetUsername sets the "username" field.
func (vu *ValidationUpdate) SetUsername(s string) *ValidationUpdate {
	vu.mutation.SetUsername(s)
	return vu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableUsername(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetUsername(*s)
	}
	return vu
}

// ClearUsername clears the value of the "username" field.
func (vu *ValidationUpdate) ClearUsername() *ValidationUpdate {
	vu.mutation.ClearUsername()
	return vu
}

// SetGroupName sets the "group_name" field.
func (vu *ValidationUpdate) SetGroupName(s string) *ValidationUpdate {
	vu.mutation.SetGroupName(s)
	return vu
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableGroupName(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetGroupName(*s)
	}
	return vu
}

// ClearGroupName clears the value of the "group_name" field.
func (vu *ValidationUpdate) ClearGroupName() *ValidationUpdate {
	vu.mutation.ClearGroupName()
	return vu
}

// SetFilePath sets the "file_path" field.
func (vu *ValidationUpdate) SetFilePath(s string) *ValidationUpdate {
	vu.mutation.SetFilePath(s)
	return vu
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableFilePath(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetFilePath(*s)
	}
	return vu
}

// ClearFilePath clears the value of the "file_path" field.
func (vu *ValidationUpdate) ClearFilePath() *ValidationUpdate {
	vu.mutation.ClearFilePath()
	return vu
}

// SetSearchString sets the "search_string" field.
func (vu *ValidationUpdate) SetSearchString(s string) *ValidationUpdate {
	vu.mutation.SetSearchString(s)
	return vu
}

// SetNillableSearchString sets the "search_string" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableSearchString(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetSearchString(*s)
	}
	return vu
}

// ClearSearchString clears the value of the "search_string" field.
func (vu *ValidationUpdate) ClearSearchString() *ValidationUpdate {
	vu.mutation.ClearSearchString()
	return vu
}

// SetServiceName sets the "service_name" field.
func (vu *ValidationUpdate) SetServiceName(s string) *ValidationUpdate {
	vu.mutation.SetServiceName(s)
	return vu
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableServiceName(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetServiceName(*s)
	}
	return vu
}

// ClearServiceName clears the value of the "service_name" field.
func (vu *ValidationUpdate) ClearServiceName() *ValidationUpdate {
	vu.mutation.ClearServiceName()
	return vu
}

// SetFilePermission sets the "file_permission" field.
func (vu *ValidationUpdate) SetFilePermission(s string) *ValidationUpdate {
	vu.mutation.SetFilePermission(s)
	return vu
}

// SetNillableFilePermission sets the "file_permission" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableFilePermission(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetFilePermission(*s)
	}
	return vu
}

// ClearFilePermission clears the value of the "file_permission" field.
func (vu *ValidationUpdate) ClearFilePermission() *ValidationUpdate {
	vu.mutation.ClearFilePermission()
	return vu
}

// SetServiceStatus sets the "service_status" field.
func (vu *ValidationUpdate) SetServiceStatus(vs validation.ServiceStatus) *ValidationUpdate {
	vu.mutation.SetServiceStatus(vs)
	return vu
}

// SetNillableServiceStatus sets the "service_status" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableServiceStatus(vs *validation.ServiceStatus) *ValidationUpdate {
	if vs != nil {
		vu.SetServiceStatus(*vs)
	}
	return vu
}

// SetProcessName sets the "process_name" field.
func (vu *ValidationUpdate) SetProcessName(s string) *ValidationUpdate {
	vu.mutation.SetProcessName(s)
	return vu
}

// SetNillableProcessName sets the "process_name" field if the given value is not nil.
func (vu *ValidationUpdate) SetNillableProcessName(s *string) *ValidationUpdate {
	if s != nil {
		vu.SetProcessName(*s)
	}
	return vu
}

// ClearProcessName clears the value of the "process_name" field.
func (vu *ValidationUpdate) ClearProcessName() *ValidationUpdate {
	vu.mutation.ClearProcessName()
	return vu
}

// AddUserIDs adds the "Users" edge to the User entity by IDs.
func (vu *ValidationUpdate) AddUserIDs(ids ...uuid.UUID) *ValidationUpdate {
	vu.mutation.AddUserIDs(ids...)
	return vu
}

// AddUsers adds the "Users" edges to the User entity.
func (vu *ValidationUpdate) AddUsers(u ...*User) *ValidationUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vu.AddUserIDs(ids...)
}

// SetEnvironmentID sets the "Environment" edge to the Environment entity by ID.
func (vu *ValidationUpdate) SetEnvironmentID(id uuid.UUID) *ValidationUpdate {
	vu.mutation.SetEnvironmentID(id)
	return vu
}

// SetNillableEnvironmentID sets the "Environment" edge to the Environment entity by ID if the given value is not nil.
func (vu *ValidationUpdate) SetNillableEnvironmentID(id *uuid.UUID) *ValidationUpdate {
	if id != nil {
		vu = vu.SetEnvironmentID(*id)
	}
	return vu
}

// SetEnvironment sets the "Environment" edge to the Environment entity.
func (vu *ValidationUpdate) SetEnvironment(e *Environment) *ValidationUpdate {
	return vu.SetEnvironmentID(e.ID)
}

// Mutation returns the ValidationMutation object of the builder.
func (vu *ValidationUpdate) Mutation() *ValidationMutation {
	return vu.mutation
}

// ClearUsers clears all "Users" edges to the User entity.
func (vu *ValidationUpdate) ClearUsers() *ValidationUpdate {
	vu.mutation.ClearUsers()
	return vu
}

// RemoveUserIDs removes the "Users" edge to User entities by IDs.
func (vu *ValidationUpdate) RemoveUserIDs(ids ...uuid.UUID) *ValidationUpdate {
	vu.mutation.RemoveUserIDs(ids...)
	return vu
}

// RemoveUsers removes "Users" edges to User entities.
func (vu *ValidationUpdate) RemoveUsers(u ...*User) *ValidationUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vu.RemoveUserIDs(ids...)
}

// ClearEnvironment clears the "Environment" edge to the Environment entity.
func (vu *ValidationUpdate) ClearEnvironment() *ValidationUpdate {
	vu.mutation.ClearEnvironment()
	return vu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vu *ValidationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vu.hooks) == 0 {
		if err = vu.check(); err != nil {
			return 0, err
		}
		affected, err = vu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ValidationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vu.check(); err != nil {
				return 0, err
			}
			vu.mutation = mutation
			affected, err = vu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vu.hooks) - 1; i >= 0; i-- {
			if vu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (vu *ValidationUpdate) SaveX(ctx context.Context) int {
	affected, err := vu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vu *ValidationUpdate) Exec(ctx context.Context) error {
	_, err := vu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vu *ValidationUpdate) ExecX(ctx context.Context) {
	if err := vu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vu *ValidationUpdate) check() error {
	if v, ok := vu.mutation.ValidationType(); ok {
		if err := validation.ValidationTypeValidator(v); err != nil {
			return &ValidationError{Name: "validation_type", err: fmt.Errorf(`ent: validator failed for field "Validation.validation_type": %w`, err)}
		}
	}
	if v, ok := vu.mutation.ServiceStatus(); ok {
		if err := validation.ServiceStatusValidator(v); err != nil {
			return &ValidationError{Name: "service_status", err: fmt.Errorf(`ent: validator failed for field "Validation.service_status": %w`, err)}
		}
	}
	return nil
}

func (vu *ValidationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   validation.Table,
			Columns: validation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: validation.FieldID,
			},
		},
	}
	if ps := vu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vu.mutation.HclID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldHclID,
		})
	}
	if value, ok := vu.mutation.ValidationType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: validation.FieldValidationType,
		})
	}
	if value, ok := vu.mutation.Hash(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldHash,
		})
	}
	if vu.mutation.HashCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldHash,
		})
	}
	if value, ok := vu.mutation.Regex(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldRegex,
		})
	}
	if vu.mutation.RegexCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldRegex,
		})
	}
	if value, ok := vu.mutation.IP(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldIP,
		})
	}
	if vu.mutation.IPCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldIP,
		})
	}
	if value, ok := vu.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldURL,
		})
	}
	if vu.mutation.URLCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldURL,
		})
	}
	if value, ok := vu.mutation.Port(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: validation.FieldPort,
		})
	}
	if value, ok := vu.mutation.AddedPort(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: validation.FieldPort,
		})
	}
	if vu.mutation.PortCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: validation.FieldPort,
		})
	}
	if value, ok := vu.mutation.Hostname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldHostname,
		})
	}
	if vu.mutation.HostnameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldHostname,
		})
	}
	if value, ok := vu.mutation.Nameservers(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: validation.FieldNameservers,
		})
	}
	if vu.mutation.NameserversCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: validation.FieldNameservers,
		})
	}
	if value, ok := vu.mutation.PackageName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldPackageName,
		})
	}
	if vu.mutation.PackageNameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldPackageName,
		})
	}
	if value, ok := vu.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldUsername,
		})
	}
	if vu.mutation.UsernameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldUsername,
		})
	}
	if value, ok := vu.mutation.GroupName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldGroupName,
		})
	}
	if vu.mutation.GroupNameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldGroupName,
		})
	}
	if value, ok := vu.mutation.FilePath(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldFilePath,
		})
	}
	if vu.mutation.FilePathCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldFilePath,
		})
	}
	if value, ok := vu.mutation.SearchString(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldSearchString,
		})
	}
	if vu.mutation.SearchStringCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldSearchString,
		})
	}
	if value, ok := vu.mutation.ServiceName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldServiceName,
		})
	}
	if vu.mutation.ServiceNameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldServiceName,
		})
	}
	if value, ok := vu.mutation.FilePermission(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldFilePermission,
		})
	}
	if vu.mutation.FilePermissionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldFilePermission,
		})
	}
	if value, ok := vu.mutation.ServiceStatus(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: validation.FieldServiceStatus,
		})
	}
	if value, ok := vu.mutation.ProcessName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldProcessName,
		})
	}
	if vu.mutation.ProcessNameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldProcessName,
		})
	}
	if vu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   validation.UsersTable,
			Columns: []string{validation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !vu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   validation.UsersTable,
			Columns: []string{validation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   validation.UsersTable,
			Columns: []string{validation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vu.mutation.EnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   validation.EnvironmentTable,
			Columns: []string{validation.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: environment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   validation.EnvironmentTable,
			Columns: []string{validation.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: environment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{validation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ValidationUpdateOne is the builder for updating a single Validation entity.
type ValidationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ValidationMutation
}

// SetHclID sets the "hcl_id" field.
func (vuo *ValidationUpdateOne) SetHclID(s string) *ValidationUpdateOne {
	vuo.mutation.SetHclID(s)
	return vuo
}

// SetValidationType sets the "validation_type" field.
func (vuo *ValidationUpdateOne) SetValidationType(vt validation.ValidationType) *ValidationUpdateOne {
	vuo.mutation.SetValidationType(vt)
	return vuo
}

// SetHash sets the "hash" field.
func (vuo *ValidationUpdateOne) SetHash(s string) *ValidationUpdateOne {
	vuo.mutation.SetHash(s)
	return vuo
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableHash(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetHash(*s)
	}
	return vuo
}

// ClearHash clears the value of the "hash" field.
func (vuo *ValidationUpdateOne) ClearHash() *ValidationUpdateOne {
	vuo.mutation.ClearHash()
	return vuo
}

// SetRegex sets the "regex" field.
func (vuo *ValidationUpdateOne) SetRegex(s string) *ValidationUpdateOne {
	vuo.mutation.SetRegex(s)
	return vuo
}

// SetNillableRegex sets the "regex" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableRegex(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetRegex(*s)
	}
	return vuo
}

// ClearRegex clears the value of the "regex" field.
func (vuo *ValidationUpdateOne) ClearRegex() *ValidationUpdateOne {
	vuo.mutation.ClearRegex()
	return vuo
}

// SetIP sets the "ip" field.
func (vuo *ValidationUpdateOne) SetIP(s string) *ValidationUpdateOne {
	vuo.mutation.SetIP(s)
	return vuo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableIP(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetIP(*s)
	}
	return vuo
}

// ClearIP clears the value of the "ip" field.
func (vuo *ValidationUpdateOne) ClearIP() *ValidationUpdateOne {
	vuo.mutation.ClearIP()
	return vuo
}

// SetURL sets the "url" field.
func (vuo *ValidationUpdateOne) SetURL(s string) *ValidationUpdateOne {
	vuo.mutation.SetURL(s)
	return vuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableURL(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetURL(*s)
	}
	return vuo
}

// ClearURL clears the value of the "url" field.
func (vuo *ValidationUpdateOne) ClearURL() *ValidationUpdateOne {
	vuo.mutation.ClearURL()
	return vuo
}

// SetPort sets the "port" field.
func (vuo *ValidationUpdateOne) SetPort(i int) *ValidationUpdateOne {
	vuo.mutation.ResetPort()
	vuo.mutation.SetPort(i)
	return vuo
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillablePort(i *int) *ValidationUpdateOne {
	if i != nil {
		vuo.SetPort(*i)
	}
	return vuo
}

// AddPort adds i to the "port" field.
func (vuo *ValidationUpdateOne) AddPort(i int) *ValidationUpdateOne {
	vuo.mutation.AddPort(i)
	return vuo
}

// ClearPort clears the value of the "port" field.
func (vuo *ValidationUpdateOne) ClearPort() *ValidationUpdateOne {
	vuo.mutation.ClearPort()
	return vuo
}

// SetHostname sets the "hostname" field.
func (vuo *ValidationUpdateOne) SetHostname(s string) *ValidationUpdateOne {
	vuo.mutation.SetHostname(s)
	return vuo
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableHostname(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetHostname(*s)
	}
	return vuo
}

// ClearHostname clears the value of the "hostname" field.
func (vuo *ValidationUpdateOne) ClearHostname() *ValidationUpdateOne {
	vuo.mutation.ClearHostname()
	return vuo
}

// SetNameservers sets the "nameservers" field.
func (vuo *ValidationUpdateOne) SetNameservers(s []string) *ValidationUpdateOne {
	vuo.mutation.SetNameservers(s)
	return vuo
}

// ClearNameservers clears the value of the "nameservers" field.
func (vuo *ValidationUpdateOne) ClearNameservers() *ValidationUpdateOne {
	vuo.mutation.ClearNameservers()
	return vuo
}

// SetPackageName sets the "package_name" field.
func (vuo *ValidationUpdateOne) SetPackageName(s string) *ValidationUpdateOne {
	vuo.mutation.SetPackageName(s)
	return vuo
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillablePackageName(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetPackageName(*s)
	}
	return vuo
}

// ClearPackageName clears the value of the "package_name" field.
func (vuo *ValidationUpdateOne) ClearPackageName() *ValidationUpdateOne {
	vuo.mutation.ClearPackageName()
	return vuo
}

// SetUsername sets the "username" field.
func (vuo *ValidationUpdateOne) SetUsername(s string) *ValidationUpdateOne {
	vuo.mutation.SetUsername(s)
	return vuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableUsername(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetUsername(*s)
	}
	return vuo
}

// ClearUsername clears the value of the "username" field.
func (vuo *ValidationUpdateOne) ClearUsername() *ValidationUpdateOne {
	vuo.mutation.ClearUsername()
	return vuo
}

// SetGroupName sets the "group_name" field.
func (vuo *ValidationUpdateOne) SetGroupName(s string) *ValidationUpdateOne {
	vuo.mutation.SetGroupName(s)
	return vuo
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableGroupName(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetGroupName(*s)
	}
	return vuo
}

// ClearGroupName clears the value of the "group_name" field.
func (vuo *ValidationUpdateOne) ClearGroupName() *ValidationUpdateOne {
	vuo.mutation.ClearGroupName()
	return vuo
}

// SetFilePath sets the "file_path" field.
func (vuo *ValidationUpdateOne) SetFilePath(s string) *ValidationUpdateOne {
	vuo.mutation.SetFilePath(s)
	return vuo
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableFilePath(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetFilePath(*s)
	}
	return vuo
}

// ClearFilePath clears the value of the "file_path" field.
func (vuo *ValidationUpdateOne) ClearFilePath() *ValidationUpdateOne {
	vuo.mutation.ClearFilePath()
	return vuo
}

// SetSearchString sets the "search_string" field.
func (vuo *ValidationUpdateOne) SetSearchString(s string) *ValidationUpdateOne {
	vuo.mutation.SetSearchString(s)
	return vuo
}

// SetNillableSearchString sets the "search_string" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableSearchString(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetSearchString(*s)
	}
	return vuo
}

// ClearSearchString clears the value of the "search_string" field.
func (vuo *ValidationUpdateOne) ClearSearchString() *ValidationUpdateOne {
	vuo.mutation.ClearSearchString()
	return vuo
}

// SetServiceName sets the "service_name" field.
func (vuo *ValidationUpdateOne) SetServiceName(s string) *ValidationUpdateOne {
	vuo.mutation.SetServiceName(s)
	return vuo
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableServiceName(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetServiceName(*s)
	}
	return vuo
}

// ClearServiceName clears the value of the "service_name" field.
func (vuo *ValidationUpdateOne) ClearServiceName() *ValidationUpdateOne {
	vuo.mutation.ClearServiceName()
	return vuo
}

// SetFilePermission sets the "file_permission" field.
func (vuo *ValidationUpdateOne) SetFilePermission(s string) *ValidationUpdateOne {
	vuo.mutation.SetFilePermission(s)
	return vuo
}

// SetNillableFilePermission sets the "file_permission" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableFilePermission(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetFilePermission(*s)
	}
	return vuo
}

// ClearFilePermission clears the value of the "file_permission" field.
func (vuo *ValidationUpdateOne) ClearFilePermission() *ValidationUpdateOne {
	vuo.mutation.ClearFilePermission()
	return vuo
}

// SetServiceStatus sets the "service_status" field.
func (vuo *ValidationUpdateOne) SetServiceStatus(vs validation.ServiceStatus) *ValidationUpdateOne {
	vuo.mutation.SetServiceStatus(vs)
	return vuo
}

// SetNillableServiceStatus sets the "service_status" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableServiceStatus(vs *validation.ServiceStatus) *ValidationUpdateOne {
	if vs != nil {
		vuo.SetServiceStatus(*vs)
	}
	return vuo
}

// SetProcessName sets the "process_name" field.
func (vuo *ValidationUpdateOne) SetProcessName(s string) *ValidationUpdateOne {
	vuo.mutation.SetProcessName(s)
	return vuo
}

// SetNillableProcessName sets the "process_name" field if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableProcessName(s *string) *ValidationUpdateOne {
	if s != nil {
		vuo.SetProcessName(*s)
	}
	return vuo
}

// ClearProcessName clears the value of the "process_name" field.
func (vuo *ValidationUpdateOne) ClearProcessName() *ValidationUpdateOne {
	vuo.mutation.ClearProcessName()
	return vuo
}

// AddUserIDs adds the "Users" edge to the User entity by IDs.
func (vuo *ValidationUpdateOne) AddUserIDs(ids ...uuid.UUID) *ValidationUpdateOne {
	vuo.mutation.AddUserIDs(ids...)
	return vuo
}

// AddUsers adds the "Users" edges to the User entity.
func (vuo *ValidationUpdateOne) AddUsers(u ...*User) *ValidationUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vuo.AddUserIDs(ids...)
}

// SetEnvironmentID sets the "Environment" edge to the Environment entity by ID.
func (vuo *ValidationUpdateOne) SetEnvironmentID(id uuid.UUID) *ValidationUpdateOne {
	vuo.mutation.SetEnvironmentID(id)
	return vuo
}

// SetNillableEnvironmentID sets the "Environment" edge to the Environment entity by ID if the given value is not nil.
func (vuo *ValidationUpdateOne) SetNillableEnvironmentID(id *uuid.UUID) *ValidationUpdateOne {
	if id != nil {
		vuo = vuo.SetEnvironmentID(*id)
	}
	return vuo
}

// SetEnvironment sets the "Environment" edge to the Environment entity.
func (vuo *ValidationUpdateOne) SetEnvironment(e *Environment) *ValidationUpdateOne {
	return vuo.SetEnvironmentID(e.ID)
}

// Mutation returns the ValidationMutation object of the builder.
func (vuo *ValidationUpdateOne) Mutation() *ValidationMutation {
	return vuo.mutation
}

// ClearUsers clears all "Users" edges to the User entity.
func (vuo *ValidationUpdateOne) ClearUsers() *ValidationUpdateOne {
	vuo.mutation.ClearUsers()
	return vuo
}

// RemoveUserIDs removes the "Users" edge to User entities by IDs.
func (vuo *ValidationUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *ValidationUpdateOne {
	vuo.mutation.RemoveUserIDs(ids...)
	return vuo
}

// RemoveUsers removes "Users" edges to User entities.
func (vuo *ValidationUpdateOne) RemoveUsers(u ...*User) *ValidationUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vuo.RemoveUserIDs(ids...)
}

// ClearEnvironment clears the "Environment" edge to the Environment entity.
func (vuo *ValidationUpdateOne) ClearEnvironment() *ValidationUpdateOne {
	vuo.mutation.ClearEnvironment()
	return vuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vuo *ValidationUpdateOne) Select(field string, fields ...string) *ValidationUpdateOne {
	vuo.fields = append([]string{field}, fields...)
	return vuo
}

// Save executes the query and returns the updated Validation entity.
func (vuo *ValidationUpdateOne) Save(ctx context.Context) (*Validation, error) {
	var (
		err  error
		node *Validation
	)
	if len(vuo.hooks) == 0 {
		if err = vuo.check(); err != nil {
			return nil, err
		}
		node, err = vuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ValidationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vuo.check(); err != nil {
				return nil, err
			}
			vuo.mutation = mutation
			node, err = vuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(vuo.hooks) - 1; i >= 0; i-- {
			if vuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, vuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Validation)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ValidationMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (vuo *ValidationUpdateOne) SaveX(ctx context.Context) *Validation {
	node, err := vuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vuo *ValidationUpdateOne) Exec(ctx context.Context) error {
	_, err := vuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuo *ValidationUpdateOne) ExecX(ctx context.Context) {
	if err := vuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vuo *ValidationUpdateOne) check() error {
	if v, ok := vuo.mutation.ValidationType(); ok {
		if err := validation.ValidationTypeValidator(v); err != nil {
			return &ValidationError{Name: "validation_type", err: fmt.Errorf(`ent: validator failed for field "Validation.validation_type": %w`, err)}
		}
	}
	if v, ok := vuo.mutation.ServiceStatus(); ok {
		if err := validation.ServiceStatusValidator(v); err != nil {
			return &ValidationError{Name: "service_status", err: fmt.Errorf(`ent: validator failed for field "Validation.service_status": %w`, err)}
		}
	}
	return nil
}

func (vuo *ValidationUpdateOne) sqlSave(ctx context.Context) (_node *Validation, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   validation.Table,
			Columns: validation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: validation.FieldID,
			},
		},
	}
	id, ok := vuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Validation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, validation.FieldID)
		for _, f := range fields {
			if !validation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != validation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vuo.mutation.HclID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldHclID,
		})
	}
	if value, ok := vuo.mutation.ValidationType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: validation.FieldValidationType,
		})
	}
	if value, ok := vuo.mutation.Hash(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldHash,
		})
	}
	if vuo.mutation.HashCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldHash,
		})
	}
	if value, ok := vuo.mutation.Regex(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldRegex,
		})
	}
	if vuo.mutation.RegexCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldRegex,
		})
	}
	if value, ok := vuo.mutation.IP(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldIP,
		})
	}
	if vuo.mutation.IPCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldIP,
		})
	}
	if value, ok := vuo.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldURL,
		})
	}
	if vuo.mutation.URLCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldURL,
		})
	}
	if value, ok := vuo.mutation.Port(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: validation.FieldPort,
		})
	}
	if value, ok := vuo.mutation.AddedPort(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: validation.FieldPort,
		})
	}
	if vuo.mutation.PortCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: validation.FieldPort,
		})
	}
	if value, ok := vuo.mutation.Hostname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldHostname,
		})
	}
	if vuo.mutation.HostnameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldHostname,
		})
	}
	if value, ok := vuo.mutation.Nameservers(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: validation.FieldNameservers,
		})
	}
	if vuo.mutation.NameserversCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: validation.FieldNameservers,
		})
	}
	if value, ok := vuo.mutation.PackageName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldPackageName,
		})
	}
	if vuo.mutation.PackageNameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldPackageName,
		})
	}
	if value, ok := vuo.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldUsername,
		})
	}
	if vuo.mutation.UsernameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldUsername,
		})
	}
	if value, ok := vuo.mutation.GroupName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldGroupName,
		})
	}
	if vuo.mutation.GroupNameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldGroupName,
		})
	}
	if value, ok := vuo.mutation.FilePath(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldFilePath,
		})
	}
	if vuo.mutation.FilePathCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldFilePath,
		})
	}
	if value, ok := vuo.mutation.SearchString(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldSearchString,
		})
	}
	if vuo.mutation.SearchStringCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldSearchString,
		})
	}
	if value, ok := vuo.mutation.ServiceName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldServiceName,
		})
	}
	if vuo.mutation.ServiceNameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldServiceName,
		})
	}
	if value, ok := vuo.mutation.FilePermission(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldFilePermission,
		})
	}
	if vuo.mutation.FilePermissionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldFilePermission,
		})
	}
	if value, ok := vuo.mutation.ServiceStatus(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: validation.FieldServiceStatus,
		})
	}
	if value, ok := vuo.mutation.ProcessName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: validation.FieldProcessName,
		})
	}
	if vuo.mutation.ProcessNameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: validation.FieldProcessName,
		})
	}
	if vuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   validation.UsersTable,
			Columns: []string{validation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !vuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   validation.UsersTable,
			Columns: []string{validation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   validation.UsersTable,
			Columns: []string{validation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vuo.mutation.EnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   validation.EnvironmentTable,
			Columns: []string{validation.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: environment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   validation.EnvironmentTable,
			Columns: []string{validation.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: environment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Validation{config: vuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{validation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
