// Code generated by ent, DO NOT EDIT.

package replaypcap

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the replaypcap type in the database.
	Label = "replay_pcap"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHclID holds the string denoting the hcl_id field in the database.
	FieldHclID = "hcl_id"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldTemplate holds the string denoting the template field in the database.
	FieldTemplate = "template"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldAbsPath holds the string denoting the abs_path field in the database.
	FieldAbsPath = "abs_path"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// EdgeEnvironment holds the string denoting the environment edge name in mutations.
	EdgeEnvironment = "Environment"
	// Table holds the table name of the replaypcap in the database.
	Table = "replay_pcaps"
	// EnvironmentTable is the table that holds the Environment relation/edge.
	EnvironmentTable = "replay_pcaps"
	// EnvironmentInverseTable is the table name for the Environment entity.
	// It exists in this package in order to avoid circular dependency with the "environment" package.
	EnvironmentInverseTable = "environments"
	// EnvironmentColumn is the table column denoting the Environment relation/edge.
	EnvironmentColumn = "environment_replay_pcaps"
)

// Columns holds all SQL columns for replaypcap fields.
var Columns = []string{
	FieldID,
	FieldHclID,
	FieldSourceType,
	FieldSource,
	FieldTemplate,
	FieldDisabled,
	FieldAbsPath,
	FieldTags,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "replay_pcaps"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"environment_replay_pcaps",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
