// Code generated by ent, DO NOT EDIT.

package validation

import (
	"fmt"
	"io"
	"strconv"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the validation type in the database.
	Label = "validation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHCLID holds the string denoting the hcl_id field in the database.
	FieldHCLID = "hcl_id"
	// FieldValidationType holds the string denoting the validation_type field in the database.
	FieldValidationType = "validation_type"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldRegex holds the string denoting the regex field in the database.
	FieldRegex = "regex"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldNameservers holds the string denoting the nameservers field in the database.
	FieldNameservers = "nameservers"
	// FieldPackageName holds the string denoting the package_name field in the database.
	FieldPackageName = "package_name"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldFilePath holds the string denoting the file_path field in the database.
	FieldFilePath = "file_path"
	// FieldSearchString holds the string denoting the search_string field in the database.
	FieldSearchString = "search_string"
	// FieldServiceName holds the string denoting the service_name field in the database.
	FieldServiceName = "service_name"
	// FieldFilePermission holds the string denoting the file_permission field in the database.
	FieldFilePermission = "file_permission"
	// FieldServiceStatus holds the string denoting the service_status field in the database.
	FieldServiceStatus = "service_status"
	// FieldProcessName holds the string denoting the process_name field in the database.
	FieldProcessName = "process_name"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "Users"
	// EdgeEnvironment holds the string denoting the environment edge name in mutations.
	EdgeEnvironment = "Environment"
	// Table holds the table name of the validation in the database.
	Table = "validations"
	// UsersTable is the table that holds the Users relation/edge.
	UsersTable = "users"
	// UsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsersInverseTable = "users"
	// UsersColumn is the table column denoting the Users relation/edge.
	UsersColumn = "validation_users"
	// EnvironmentTable is the table that holds the Environment relation/edge.
	EnvironmentTable = "validations"
	// EnvironmentInverseTable is the table name for the Environment entity.
	// It exists in this package in order to avoid circular dependency with the "environment" package.
	EnvironmentInverseTable = "environments"
	// EnvironmentColumn is the table column denoting the Environment relation/edge.
	EnvironmentColumn = "environment_validations"
)

// Columns holds all SQL columns for validation fields.
var Columns = []string{
	FieldID,
	FieldHCLID,
	FieldValidationType,
	FieldHash,
	FieldRegex,
	FieldIP,
	FieldURL,
	FieldPort,
	FieldHostname,
	FieldNameservers,
	FieldPackageName,
	FieldUsername,
	FieldGroupName,
	FieldFilePath,
	FieldSearchString,
	FieldServiceName,
	FieldFilePermission,
	FieldServiceStatus,
	FieldProcessName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "validations"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"environment_validations",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ValidationType defines the type for the "validation_type" enum field.
type ValidationType string

// ValidationType values.
const (
	ValidationTypeLinuxAptInstalled   ValidationType = "linux-apt-installed"
	ValidationTypeNetTCPOpen          ValidationType = "net-tcp-open"
	ValidationTypeNetUDPOpen          ValidationType = "net-udp-open"
	ValidationTypeNetHTTPContentRegex ValidationType = "net-http-content-regex"
	ValidationTypeFileExists          ValidationType = "file-exists"
	ValidationTypeFileHash            ValidationType = "file-hash"
	ValidationTypeFileContentRegex    ValidationType = "file-content-regex"
	ValidationTypeDirExists           ValidationType = "dir-exists"
	ValidationTypeUserExists          ValidationType = "user-exists"
	ValidationTypeUserGroupMembership ValidationType = "user-group-membership"
	ValidationTypeHostPortOpen        ValidationType = "host-port-open"
	ValidationTypeHostProcessRunning  ValidationType = "host-process-running"
	ValidationTypeHostServiceState    ValidationType = "host-service-state"
	ValidationTypeNetIcmp             ValidationType = "net-icmp"
	ValidationTypeFileContentString   ValidationType = "file-content-string"
	ValidationTypeFilePermission      ValidationType = "file-permission"
)

func (vt ValidationType) String() string {
	return string(vt)
}

// ValidationTypeValidator is a validator for the "validation_type" field enum values. It is called by the builders before save.
func ValidationTypeValidator(vt ValidationType) error {
	switch vt {
	case ValidationTypeLinuxAptInstalled, ValidationTypeNetTCPOpen, ValidationTypeNetUDPOpen, ValidationTypeNetHTTPContentRegex, ValidationTypeFileExists, ValidationTypeFileHash, ValidationTypeFileContentRegex, ValidationTypeDirExists, ValidationTypeUserExists, ValidationTypeUserGroupMembership, ValidationTypeHostPortOpen, ValidationTypeHostProcessRunning, ValidationTypeHostServiceState, ValidationTypeNetIcmp, ValidationTypeFileContentString, ValidationTypeFilePermission:
		return nil
	default:
		return fmt.Errorf("validation: invalid enum value for validation_type field: %q", vt)
	}
}

// ServiceStatus defines the type for the "service_status" enum field.
type ServiceStatus string

// ServiceStatusActive is the default value of the ServiceStatus enum.
const DefaultServiceStatus = ServiceStatusActive

// ServiceStatus values.
const (
	ServiceStatusActive   ServiceStatus = "active"
	ServiceStatusInactive ServiceStatus = "inactive"
	ServiceStatusEnabled  ServiceStatus = "enabled"
	ServiceStatusDisabled ServiceStatus = "disabled"
	ServiceStatusStatic   ServiceStatus = "static"
	ServiceStatusMasked   ServiceStatus = "masked"
	ServiceStatusAlias    ServiceStatus = "alias"
	ServiceStatusLinked   ServiceStatus = "linked"
)

func (ss ServiceStatus) String() string {
	return string(ss)
}

// ServiceStatusValidator is a validator for the "service_status" field enum values. It is called by the builders before save.
func ServiceStatusValidator(ss ServiceStatus) error {
	switch ss {
	case ServiceStatusActive, ServiceStatusInactive, ServiceStatusEnabled, ServiceStatusDisabled, ServiceStatusStatic, ServiceStatusMasked, ServiceStatusAlias, ServiceStatusLinked:
		return nil
	default:
		return fmt.Errorf("validation: invalid enum value for service_status field: %q", ss)
	}
}

// OrderOption defines the ordering options for the Validation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHCLID orders the results by the hcl_id field.
func ByHCLID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHCLID, opts...).ToFunc()
}

// ByValidationType orders the results by the validation_type field.
func ByValidationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidationType, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByRegex orders the results by the regex field.
func ByRegex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegex, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByPackageName orders the results by the package_name field.
func ByPackageName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackageName, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByFilePath orders the results by the file_path field.
func ByFilePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilePath, opts...).ToFunc()
}

// BySearchString orders the results by the search_string field.
func BySearchString(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSearchString, opts...).ToFunc()
}

// ByServiceName orders the results by the service_name field.
func ByServiceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceName, opts...).ToFunc()
}

// ByFilePermission orders the results by the file_permission field.
func ByFilePermission(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilePermission, opts...).ToFunc()
}

// ByServiceStatus orders the results by the service_status field.
func ByServiceStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceStatus, opts...).ToFunc()
}

// ByProcessName orders the results by the process_name field.
func ByProcessName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessName, opts...).ToFunc()
}

// ByUsersCount orders the results by Users count.
func ByUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsersStep(), opts...)
	}
}

// ByUsers orders the results by Users terms.
func ByUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEnvironmentField orders the results by Environment field.
func ByEnvironmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnvironmentStep(), sql.OrderByField(field, opts...))
	}
}
func newUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
	)
}
func newEnvironmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnvironmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EnvironmentTable, EnvironmentColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e ValidationType) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *ValidationType) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = ValidationType(str)
	if err := ValidationTypeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid ValidationType", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e ServiceStatus) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *ServiceStatus) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = ServiceStatus(str)
	if err := ServiceStatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid ServiceStatus", str)
	}
	return nil
}
